services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: e-commerce-template
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
